### PR TITLE
Fix style bug

### PR DESCRIPTION
**Pull request by Gninoskcaj**
Fix the style bug and create random component

### CODE REVIEW

**Comment by Vehmloewff** [comment]
Nice!

I Think it would be nice if `random` was in it's own module.

It would also be good to write a test for it, just in case something changes.

**Comment by Gninoskcaj** [comment]
> It would also be good to write a test for it, just in case something changes.

@Vehmloewff Do you want me to check if `random()` returns a `string`?

**Comment by Vehmloewff** [comment]
Yes, if it returns a string that is the right length.  Also it must not return any illegal chars. (`.`, `#`, `@`, `!`, etc.)

**Comment by Vehmloewff** [comment]
You can do something like this:
```js
expect(id).toMatch(/^[a-z0-9]$/);
expect(id.length).toBe(10);
```

**Pull request merged**
